BLBNE_TO!!!!!!!!!!!!!!: '********************************'
_MIN_ACCESS_TOKEN_TIME: 30
gocdb_public_url: https://goc.egi.eu/gocdbpi/public/
gocdb_service_group: org.openstack.nova
log_config_file: /home/jaro221/.config/fedcloud/logging.conf
log_file: /home/jaro221/.config/fedcloud/logs/fedcloud.log
log_level: DEBUG
min_access_token_time: 30
mytoken: eyJhbGciOiJFUzUxMiIsInR5cCI6Ik1UK0pXVCJ9.eyJ2ZXIiOiIwLjciLCJ0b2tlbl90eXBlIjoibXl0b2tlbiIsImlzcyI6Imh0dHBzOi8vbXl0b2tlbi5kYXRhLmtpdC5lZHUvIiwic3ViIjoiMzBxQ1Ztem11SDBjKzZodXRNNWVJU1JZSWNWSnVmL0tuMkRJNE9oWE05MD0iLCJzZXFfbm8iOjEsImF1ZCI6Imh0dHBzOi8vbXl0b2tlbi5kYXRhLmtpdC5lZHUvIiwib2lkY19zdWIiOiI0NzdlMDcyMGQ1MzAxYzI0NzBjODM0MjUyZjI4OGNiM2YyNDU5OGFkMzQ5MzQ3YTY1MmM2YTMyOTJmYjgyZDNjQGVnaS5ldSIsIm9pZGNfaXNzIjoiaHR0cHM6Ly9hYWkuZWdpLmV1L2F1dGgvcmVhbG1zL2VnaSIsImNhcGFiaWxpdGllcyI6WyJBVCIsInRva2VuaW5mbyJdLCJleHAiOjE3NDAwODA3MTQsIm5iZiI6MTc0MDAzNzUyNSwiaWF0IjoxNzQwMDM3NTI1LCJhdXRoX3RpbWUiOjE3NDAwMzc1MjUsImp0aSI6ImE4YmNkZTI3LTE1OWItNDFkYi1iNzY4LTIzODAwYmViNjNkZiIsInJlc3RyaWN0aW9ucyI6W3siZXhwIjoxNzQwMDgwNzE0LCJob3N0cyI6WyIxNDcuMjEzLjY1LjI1MCJdLCJ1c2FnZXNfQVQiOjEwMH1dfQ.AYRCgqDf5UtHFS-AbKgcJ5ZaoZ0qeW2fJibu2d-7J0Ja9scV11diRe8DE4KEiIBcwK985Rcjmz2Q2jVsSswi2AZrAaudoimArFW5oJTMaa7CEWFGPwfLmLRRqYXFhuMKIINEAiOJpTJkdRUDKcubX7A9r811I_9KybB_MLe4sFlUCphR
mytoken_server: https://mytoken.data.kit.edu
oidc_agent_account: jaro221
oidc_url: https://aai.egi.eu/auth/realms/egi
os_auth_type: v3oidcaccesstoken
os_identity_provider: egi.eu
os_protocol: openid
requests_cert_file: /home/jaro221/.config/fedcloud/cert/certs.pem
site: IISAS-FedCloud
site_dir: /home/jaro221/.config/fedcloud/site-config
site_list_url: https://raw.githubusercontent.com/tdviet/fedcloudclient/master/config/sites.yaml
vault_endpoint: https://vault.services.fedcloud.eu:8200
vault_locker_mount_point: /v1/cubbyhole/
vault_mount_point: /secrets/
vault_role: ''
vault_salt: fedcloud_salt
vo: vo.access.egi.eu
